version: '3'
services:
  local:
    build:
      context: .
      dockerfile: ./Dockerfile
    shm_size: 60g
    image: im2022-kaggle
    container_name: container-im2022-kaggle
    tty: true
    stdin_open: true
    command: >
      sh -c '[ ! -d /root/dotfiles ] && git clone git@github.com:daikichiba9511/dotfiles.git ~/dotfiles && cd ~/dotfiles && sh scripts/setup.sh y && zsh -l'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]
    volumes:
      - .:/workspace/working
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.ssh/:/root/.ssh
